config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :chatrooms, param: :slug
  resources :messages

  root 'home#index'

  get '/signup', to: "signup#new"
  post '/signup', to: "signup#create"

  get 'signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy"

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  # ^ will listen to web socket requests on ws://localhost:/3000/cable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false

  before_validation :sanitize, :slugify

  def to_param
    self.slug
  end

  def slugify
    self.slug = self.topic.downcase.gsub(" ", "-")
  end

  def sanitize
    self.topic = self.topic.strip
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :chatrooms, through: :messages
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_user, :logged_in?

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  protected

  def authenticate_user!
    redirect_to root_path unless logged_in?
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all
  end

  def new
    @chatroom = Chatroom.new
  end

  def edit
    @chatroom = Chatroom.find_by(slug: params[:slug])
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)

    if @chatroom.save
      respond_to do |format|
        format.html { redirect_to @chatroom }
        format.js
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["a chatroom with this topic already exists"]}
        format.html { redirect_to new_chatroom_path }
      end
    end
  end

  def update
    chatroom = Chatroom.find_by(slug: params[:slug])
    chatroom.update(chatroom_params)
    redirect_to chatroom
  end

  def show
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @message = Message.new
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:topic)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  layout 'no_margin'

  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message      = Message.new(message_params)
    message.user = current_user
    chatroom     = Chatroom.find_by(id: message_params[:chatroom_id])

    if message.save
      ActionCable.server.broadcast(
        'messages',
        message: message.content,
        user: message.user.username
      )
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :chatroom_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    user = User.find_by(user_params)
    if user
      session[:user_id] = user.id
      redirect_to chatrooms_path
    else
      redirect_to signin_path, notice: 'Username does not exist'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to chatrooms_path
    else
      redirect_to signup_path, flash[:notice] =  user.errors.messages
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/_chatroom.html.slim
li= link_to chatroom.topic, chatroom_path(chatroom)

app/views/chatrooms/_chatroom_form.html.slim
.chatroom-form
  = form_for chatroom, remote: true do |f|
    .input-group
      span.input-group-addon Set a topic:
      = f.text_field :topic, class: "form-control"
    = f.submit 'Create', class: 'btn btn-primary', id: 'create-chatroom'

app/views/chatrooms/index.html.slim
.row
  .col-md-12.mt20
      h5.mt20 List of Chatrooms
      ul#chatroom-index.mt20
        - if @chatrooms.any?
          = render @chatrooms
        - else
          p Be the first one to make a chatroom!

app/views/chatrooms/new.html.slim
.row
  .col-md-12
    h5 Create an Uzap community!
    .well.mt20
      .chatroom-form
        = form_for @chatroom do |f|
          .input-group
            span.input-group-addon Set the topic:
            = f.text_field :topic, class: "form-control"
          = f.submit class: "btn btn-primary", id: "create-chatroom"

app/views/chatrooms/show.html.slim
.row.col-md-8.col-md-offset-2
  h4= @chatroom.topic
  .panel.panel-default
    - if @chatroom.messages.any?
      #messages.panel-body
        = render partial: 'messages/message', collection: @chatroom.messages
    - else
      #messages.panel-body.hidden
  = render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}

app/views/home/index.html.slim
#index-banner.parallax-container style='background: #e5fff8;'
  .section.no-pad-bot
    .container
      br/
      br/
      / h1.header.center.teal-text.text-lighten-2 Uzap
      .row.center= image_tag('http://www.enricort.me/wp-content/uploads/2017/08/uzap_fin5.gif')
      .row.center
        - if current_user
          = link_to 'Get Started', chatrooms_path, class: 'download-button btn-large waves-effect waves-light teal lighten-1'
      br/
      br/
  .parallax
    img alt=("Unsplashed background img 1") src="/assets/comp.jpg" /
.container
  .section
    /! Icon Section
    .row
      .col.s12.m4
        .icon-block
          h2.center.brown-text
            i.material-icons group
          h5.center Sign up
          p.light.text-center Create an account to meet new Uzap peeps
      .col.s12.m4
        .icon-block
          h2.center.brown-text
            i.material-icons local_dining
          h5.center Create or Join a chatroom
          p.light.text-center Create your own chatroom or join a chatroom
      .col.s12.m4
        .icon-block
          h2.center.brown-text
            i.material-icons file_download
          h5.center Send a message
          p.light.text-center Type any message to a chatroom
.parallax-container.valign-wrapper
  .section.no-pad-bot
    .container
      .row.center
        h5.header.col.s12.light Make new friends
  .parallax
    img alt=("Unsplashed background img 2") src="/assets/friends.jpg" /
.container
  .section
    .row
      .col.s12.center
        h3
          i.mdi-content-send.brown-text
        h4 Contact Us
        p.text-center.light
          | Send an email to
          | &nbsp;
          = link_to 'xiruki@programmer.net', 'mailto:xiruki@programmer.net'
.parallax-container.valign-wrapper
  .section.no-pad-bot
    .container
      .row.center
        h5.header.col.s12.light Sign up now to make uzap
  .parallax
    img alt=("Unsplashed background img 3") src="/assets/contact.jpg" /

app/views/layouts/application.html.slim
doctype html
html
  head
    title Uzap
    = csrf_meta_tags
    = action_cable_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/shared/navbar'
    .container
      .row
        .col.s12
          .mt10= render 'layouts/shared/alerts'
          = yield
    = render 'layouts/shared/footer'

app/views/layouts/no_margin.html.slim
doctype html
html
  head
    title Uzap
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons'
    = javascript_include_tag 'application'

  body
    = render 'layouts/shared/navbar'
    = yield
    = render 'layouts/shared/footer'

app/views/layouts/shared/_alerts.html.slim
- flash.each do |key, value|
  div class=("card-panel red lighten-3 alert alert-#{key}") = value

app/views/layouts/shared/_footer.html.slim
footer.page-footer.teal
  .footer-copyright
    .container
      .row
        .col.l6.s12
          | Developed by
          a.brown-text.text-lighten-3 href="http://xirukitepe.github.io"  Xiruki
        .col.l3.s12
        .col.l3.s12.text-right
          | Template by
          a.brown-text.text-lighten-3 href="http://materializecss.com"  Materialize

app/views/layouts/shared/_navbar.html.slim
nav.white role="navigation"
  .nav-wrapper.container
    = link_to root_path, class: 'brand-logo', id: 'logo-container' do
      i.large.material-icons face
    ul.right.hide-on-med-and-down
      - if current_user
        li= link_to 'New Chatroom', new_chatroom_path
        li= link_to 'Chatrooms', chatrooms_path
        li= link_to 'Sign out', signout_path, method: :delete
      - else
        li= link_to 'Sign up', signup_path
        li= link_to 'Sign in', signin_path
    ul#nav-mobile.side-nav
      - if current_user
        li= link_to 'New Chatroom', new_chatroom_path
        li= link_to 'Sign out', signout_path, method: :delete
      - else
        li= link_to 'Sign up', signup_path
        li= link_to 'Sign in', signin_path
    a.button-collapse data-activates="nav-mobile" href="#"
      i.material-icons menu

app/views/messages/_message.html.slim
p
  strong
    = message.user.username
    | :
    | &nbsp;
  = message.content

app/views/messages/_message_form.html.slim
= form_for message, remote: true, authenticity_token: true do |f|
  = f.label :your_message
  = f.text_area :content, class: "form-control text-area", data: { textarea: 'message' }

  = f.hidden_field :chatroom_id, value: chatroom.id
  .mt20= f.submit 'Send', class: 'btn btn-primary', data: { send: 'message' }

app/views/signup/new.html.slim
.row
  .col-md-8.col-md-offset-2
    h4#log-in-title Sign up
    .auth-form.well
      = form_for(User.new, url: signup_path) do |f|
        = f.label :username
        .input-group
          = f.text_field :username, class: "form-control"
        .actions
          = f.submit "sign up", class: "btn btn-primary"